services:
  - type: web
    name: taller-app
    env: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: Taller Mecanico
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:gYX38+2lTOTtMSCNgWFvQrr1TOFF7yeXm4CehRaNDwI=
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: taller-db
          property: connectionString
      - key: PORT
        value: 80

databases:
  - name: taller-db
    plan: free
    databaseName: taller
    user: taller
